// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4mFQcUQRVcTyPRdUtJ8_mgdfDE3shGM',
    appId: '1:5494400316:web:58cb8f998edae1ad04aa39',
    messagingSenderId: '5494400316',
    projectId: 'jejak-batik-3b408',
    authDomain: 'jejak-batik-3b408.firebaseapp.com',
    storageBucket: 'jejak-batik-3b408.firebasestorage.app',
    measurementId: 'G-PEK7LPEWWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDS93en5c8LFK4geFCuk1zvogTyTQVvoI',
    appId: '1:5494400316:android:92c8047af21f084f04aa39',
    messagingSenderId: '5494400316',
    projectId: 'jejak-batik-3b408',
    storageBucket: 'jejak-batik-3b408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGDYD5n7puzhiDgplNyLfIV3U9GjG0OM',
    appId: '1:5494400316:ios:2d43c6f7db1b9f7b04aa39',
    messagingSenderId: '5494400316',
    projectId: 'jejak-batik-3b408',
    storageBucket: 'jejak-batik-3b408.firebasestorage.app',
    iosBundleId: 'com.example.jejakBatik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZGDYD5n7puzhiDgplNyLfIV3U9GjG0OM',
    appId: '1:5494400316:ios:2d43c6f7db1b9f7b04aa39',
    messagingSenderId: '5494400316',
    projectId: 'jejak-batik-3b408',
    storageBucket: 'jejak-batik-3b408.firebasestorage.app',
    iosBundleId: 'com.example.jejakBatik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF4mFQcUQRVcTyPRdUtJ8_mgdfDE3shGM',
    appId: '1:5494400316:web:626ccd427937659804aa39',
    messagingSenderId: '5494400316',
    projectId: 'jejak-batik-3b408',
    authDomain: 'jejak-batik-3b408.firebaseapp.com',
    storageBucket: 'jejak-batik-3b408.firebasestorage.app',
    measurementId: 'G-DFQZ5D0CPK',
  );
}
